// Copyright 2024 Rubrik, Inc.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to
// deal in the Software without restriction, including without limitation the
// rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
// sell copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

package provider

const (
	keyAccessKey                                    = "access_key"
	keyAccountID                                    = "account_id"
	keyActions                                      = "actions"
	keyAdminEmail                                   = "admin_email"
	keyAdminPassword                                = "admin_password"
	keyAppID                                        = "app_id"
	keyAppName                                      = "app_name"
	keyAppSecret                                    = "app_secret"
	keyArchivalConsolidation                        = "archival_consolidation"
	keyArchivalLocationID                           = "archival_location_id"
	keyArchivalProxySettings                        = "archival_proxy_settings"
	keyARN                                          = "arn"
	keyAssumeRole                                   = "assume_role"
	keyBucketPrefix                                 = "bucket_prefix"
	keyBucketName                                   = "bucket_name"
	keyBucketTags                                   = "bucket_tags"
	keyBypassProxy                                  = "bypass_proxy"
	keyCredentials                                  = "credentials"
	keyCloud                                        = "cloud"
	keyCloudAccountID                               = "cloud_account_id"
	keyCloudAccountIDs                              = "cloud_account_ids"
	keyCloudComputeSettings                         = "cloud_compute_settings"
	keyCloudNativeArchival                          = "cloud_native_archival"
	keyCloudNativeArchivalEncryption                = "cloud_native_archival_encryption"
	keyCloudNativeBlobProtection                    = "cloud_native_blob_protection"
	keyCloudNativeProtection                        = "cloud_native_protection"
	keyClusterID                                    = "cluster_id"
	keyClusterName                                  = "cluster_name"
	keyClusterNodes                                 = "cluster_nodes"
	keyClusterNodeIPAddress                         = "cluster_node_ip_address"
	keyClusterSecurityGroupID                       = "cluster_security_group_id"
	keyComputeProxySettings                         = "compute_proxy_settings"
	keyConnectionCommand                            = "connection_command"
	keyConnectionCommandExecuted                    = "connection_command_executed"
	keyConnectionStatus                             = "connection_status"
	keyContainerName                                = "container_name"
	keyCustomerManagedKey                           = "customer_managed_key"
	keyCustomerManagedPolicies                      = "customer_managed_policies"
	keyDataActions                                  = "data_actions"
	keyDeleteSnapshotsOnDestroy                     = "delete_snapshots_on_destroy"
	keyDescription                                  = "description"
	keyDomain                                       = "domain"
	keyDomainName                                   = "domain_name"
	keyEC2RecoveryRolePath                          = "ec2_recovery_role_path"
	keyEmail                                        = "email"
	keyEnableEncryption                             = "enable_encryption"
	keyEncryptionPassword                           = "encryption_password"
	keyEndpointSettings                             = "endpoint_settings"
	keyExocompute                                   = "exocompute"
	keyExocomputeID                                 = "exocompute_id"
	keyExternalID                                   = "external_id"
	keyFeature                                      = "feature"
	keyFeatures                                     = "features"
	keyFQDN                                         = "fqdn"
	keyHash                                         = "hash"
	keyHierarchy                                    = "hierarchy"
	keyHostAccountID                                = "host_account_id"
	keyHostCloudAccountID                           = "host_cloud_account_id"
	keyID                                           = "id"
	keyImmutabilitySettings                         = "immutability_settings"
	keyInstanceProfile                              = "instance_profile"
	keyInstanceProfileKeys                          = "instance_profile_keys"
	keyIPAddresses                                  = "ip_addresses"
	keyIsAccountOwner                               = "is_account_owner"
	keyIsOrgAdmin                                   = "is_org_admin"
	keyKey                                          = "key"
	keyKMSEndpoint                                  = "kms_endpoint"
	keyKMSMasterKey                                 = "kms_master_key"
	keyLocationTemplate                             = "location_template"
	keyLockPeriod                                   = "lock_period"
	keyManagedPolicies                              = "managed_policies"
	keyManifest                                     = "manifest"
	keyName                                         = "name"
	keyNativeID                                     = "native_id"
	keyNodeConfig                                   = "node_config"
	keyNodeSecurityGroupID                          = "node_security_group_id"
	keyNotActions                                   = "not_actions"
	keyNotDataActions                               = "not_data_actions"
	keyObjectIDs                                    = "object_ids"
	keyObjectType                                   = "object_type"
	keyObjectTypes                                  = "object_types"
	keyOperation                                    = "operation"
	keyPassword                                     = "password"
	keyPermissionGroups                             = "permission_groups"
	keyPermission                                   = "permission"
	keyPermissions                                  = "permissions"
	keyPermissionsHash                              = "permissions_hash"
	keyPodOverlayNetworkCIDR                        = "pod_overlay_network_cidr"
	keyPolarisAccount                               = "polaris_account"
	keyPolarisAWSAccount                            = "polaris_aws_account"
	keyPolarisAWSArchivalLocation                   = "polaris_aws_archival_location"
	keyPolarisAWSCNPAccount                         = "polaris_aws_cnp_account"
	keyPolarisAWSCNPAccountAttachments              = "polaris_aws_cnp_account_attachments"
	keyPolarisAWSCNPAccountTrustPolicy              = "polaris_aws_cnp_account_trust_policy"
	keyPolarisAWSCNPArtifacts                       = "polaris_aws_cnp_artifacts"
	keyPolarisAWSCNPPermissions                     = "polaris_aws_cnp_permissions"
	keyPolarisAWSExocompute                         = "polaris_aws_exocompute"
	keyPolarisAWSExocomputeClusterAttachment        = "polaris_aws_exocompute_cluster_attachment"
	keyPolarisAWSPrivateContainerRegistry           = "polaris_aws_private_container_registry"
	keyPolarisAzureArchivalLocation                 = "polaris_azure_archival_location"
	keyPolarisAzureExocompute                       = "polaris_azure_exocompute"
	keyPolarisAzureExocomputeClusterAttachment      = "polaris_azure_exocompute_cluster_attachment"
	keyPolarisAzurePermissions                      = "polaris_azure_permissions"
	keyPolarisAzurePrivateContainerRegistry         = "polaris_azure_private_container_registry"
	keyPolarisAzureServicePrincipal                 = "polaris_azure_service_principal"
	keyPolarisAzureSubscription                     = "polaris_azure_subscription"
	keyPolarisCDMBootstrap                          = "polaris_cdm_bootstrap"
	keyPolarisCDMBootstrapCCESAWS                   = "polaris_cdm_bootstrap_cces_aws"
	keyPolarisCDMBootstrapCCESAzure                 = "polaris_cdm_bootstrap_cces_azure"
	keyPolarisCDMRegistration                       = "polaris_cdm_registration"
	keyPolarisCustomRole                            = "polaris_custom_role"
	keyPolarisDataCenterArchivalLocationAmazonS3    = "polaris_data_center_archival_location_amazon_s3"
	keyPolarisDataCenterAWSAccount                  = "polaris_data_center_aws_account"
	keyPolarisDataCenterAzureSubscription           = "polaris_data_center_azure_subscription"
	keyPolarisDeployment                            = "polaris_deployment"
	keyPolarisFeatures                              = "polaris_features"
	keyPolarisManaged                               = "polaris_managed"
	keyPolarisRole                                  = "polaris_role"
	keyPolarisRoleAssignment                        = "polaris_role_assignment"
	keyPolarisRoleTemplate                          = "polaris_role_template"
	keyPolarisSLADomain                             = "polaris_sla_domain"
	keyPolarisSLADomainAssignment                   = "polaris_sla_domain_assignment"
	keyPolarisSSOGroup                              = "polaris_sso_group"
	keyPolarisTagRule                               = "polaris_tag_rule"
	keyPolarisUser                                  = "polaris_user"
	keyPolicy                                       = "policy"
	keyPortNumber                                   = "port_number"
	keyProfile                                      = "profile"
	keyProtocol                                     = "protocol"
	keyProxyServer                                  = "proxy_server"
	keyRedundancy                                   = "redundancy"
	keyRegion                                       = "region"
	keyRegions                                      = "regions"
	keyRegistrationMode                             = "registration_mode"
	keyResourceGroupActions                         = "resource_group_actions"
	keyResourceGroupDataActions                     = "resource_group_data_actions"
	keyResourceGroupName                            = "resource_group_name"
	keyResourceGroupNotActions                      = "resource_group_not_actions"
	keyResourceGroupNotDataActions                  = "resource_group_not_data_actions"
	keyResourceGroupTags                            = "resource_group_tags"
	keyResourceGroupRegion                          = "resource_group_region"
	keyRetrievalTier                                = "retrieval_tier"
	keyRole                                         = "role"
	keyRoleID                                       = "role_id"
	keyRoleIDs                                      = "role_ids"
	keyRoleKey                                      = "role_key"
	keyRoleKeys                                     = "role_keys"
	keyRoles                                        = "roles"
	keyRoleTemplateID                               = "role_template_id"
	keyRSAKey                                       = "rsa_key"
	keyS3Endpoint                                   = "s3_endpoint"
	keySDKAuth                                      = "sdk_auth"
	keySecretKey                                    = "secret_key"
	keySecurityGroupID                              = "security_group_id"
	keySnappableType                                = "snappable_type"
	keySQLDBProtection                              = "sql_db_protection"
	keySQLMIProtection                              = "sql_mi_protection"
	keySetupYAML                                    = "setup_yaml"
	keySLADomainID                                  = "sla_domain_id"
	keySSOGroupID                                   = "sso_group_id"
	keyStackARN                                     = "stack_arn"
	keyStatus                                       = "status"
	keyStorageAccountNamePrefix                     = "storage_account_name_prefix"
	keyStorageAccountRegion                         = "storage_account_region"
	keyStorageAccountTags                           = "storage_account_tags"
	keyStorageClass                                 = "storage_class"
	keyStorageTier                                  = "storage_tier"
	keySubnet                                       = "subnet"
	keySubnetID                                     = "subnet_id"
	keySubnets                                      = "subnets"
	keySubscriptionActions                          = "subscription_actions"
	keySubscriptionDataActions                      = "subscription_data_actions"
	keySubscriptionID                               = "subscription_id"
	keySubscriptionName                             = "subscription_name"
	keySubscriptionNotActions                       = "subscription_not_actions"
	keySubscriptionNotDataActions                   = "subscription_not_data_actions"
	keySyncStatus                                   = "sync_status"
	keyTagAllValues                                 = "tag_all_values"
	keyTagKey                                       = "tag_key"
	keyTagValue                                     = "tag_value"
	keyTenantDomain                                 = "tenant_domain"
	keyTenantID                                     = "tenant_id"
	keyTimeout                                      = "timeout"
	keyTokenCache                                   = "token_cache"
	keyTokenCacheDir                                = "token_cache_dir"
	keyTokenCacheSecret                             = "token_cache_secret"
	keyTokenRefresh                                 = "token_refresh"
	keyURL                                          = "url"
	keyUserAssignedManagedIdentityName              = "user_assigned_managed_identity_name"
	keyUserAssignedManagedIdentityPrincipalID       = "user_assigned_managed_identity_principal_id"
	keyUserAssignedManagedIdentityRegion            = "user_assigned_managed_identity_region"
	keyUserAssignedManagedIdentityResourceGroupName = "user_assigned_managed_identity_resource_group_name"
	keyUserEmail                                    = "user_email"
	keyUserID                                       = "user_id"
	keyUsername                                     = "username"
	keyUsers                                        = "users"
	keyVaultName                                    = "vault_name"
	keyVersion                                      = "version"
	keyVPCID                                        = "vpc_id"
)
