package provider

const (
	keyAccountFQDN                   = "account_fqdn"
	keyAccountName                   = "account_name"
	keyActions                       = "actions"
	keyAppID                         = "app_id"
	keyAppName                       = "app_name"
	keyAppSecret                     = "app_secret"
	keyCredentials                   = "credentials"
	keyCloudAccountID                = "cloud_account_id"
	keyCloudNativeArchival           = "cloud_native_archival"
	keyCloudNativeArchivalEncryption = "cloud_native_archival_encryption"
	keyCloudNativeProtection         = "cloud_native_protection"
	keyDataActions                   = "data_actions"
	keyDeleteSnapshotsOnDestroy      = "delete_snapshots_on_destroy"
	keyExocompute                    = "exocompute"
	keyFeatures                      = "features"
	keyHash                          = "hash"
	keyID                            = "id"
	keyIPAddresses                   = "ip_addresses"
	keyNotActions                    = "not_actions"
	keyNotDataActions                = "not_data_actions"
	keyPermissions                   = "permissions"
	keyPermissionsHash               = "permissions_hash"
	keyPolarisAzureExocompute        = "polaris_azure_exocompute"
	keyPolarisAzurePermissions       = "polaris_azure_permissions"
	keyPolarisAzureServicePrincipal  = "polaris_azure_service_principal"
	keyPolarisAzureSubscription      = "polaris_azure_subscription"
	keyPolarisDeployment             = "polaris_deployment"
	keyPolarisFeatures               = "polaris_features"
	keyRegion                        = "region"
	keyRegions                       = "regions"
	keyResourceGroupName             = "resource_group_name"
	keyResourceGroupTags             = "resource_group_tags"
	keyResourceGroupRegion           = "resource_group_region"
	keySDKAuth                       = "sdk_auth"
	keySQLDBProtection               = "sql_db_protection"
	keySQLMIProtection               = "sql_mi_protection"
	keyStatus                        = "status"
	keySubnet                        = "subnet"
	keySubscriptionID                = "subscription_id"
	keySubscriptionName              = "subscription_name"
	keyTenantDomain                  = "tenant_domain"
	keyTenantID                      = "tenant_id"
	keyVersion                       = "version"
)
