package provider

const (
	keyActions                       = "actions"
	keyAppID                         = "app_id"
	keyAppName                       = "app_name"
	keyAppSecret                     = "app_secret"
	keyAzureExocompute               = "polaris_azure_exocompute"
	keyAzurePermissions              = "polaris_azure_permissions"
	keyAzureServicePrincipal         = "polaris_azure_service_principal"
	keyAzureSubscription             = "polaris_azure_subscription"
	keyCredentials                   = "credentials"
	keyCloudAccountID                = "cloud_account_id"
	keyCloudNativeArchival           = "cloud_native_archival"
	keyCloudNativeArchivalEncryption = "cloud_native_archival_encryption"
	keyCloudNativeProtection         = "cloud_native_protection"
	keyDataActions                   = "data_actions"
	keyDeleteSnapshotsOnDestroy      = "delete_snapshots_on_destroy"
	keyExocompute                    = "exocompute"
	keyFeatures                      = "features"
	keyHash                          = "hash"
	keyID                            = "id"
	keyNotActions                    = "not_actions"
	keyNotDataActions                = "not_data_actions"
	keyPermissions                   = "permissions"
	keyPermissionsHash               = "permissions_hash"
	keyRegion                        = "region"
	keyRegions                       = "regions"
	keyResourceGroupName             = "resource_group_name"
	keyResourceGroupTags             = "resource_group_tags"
	keyResourceGroupRegion           = "resource_group_region"
	keySDKAuth                       = "sdk_auth"
	keySQLDBProtection               = "sql_db_protection"
	keySQLMIProtection               = "sql_mi_protection"
	keyStatus                        = "status"
	keySubnet                        = "subnet"
	keySubscriptionID                = "subscription_id"
	keySubscriptionName              = "subscription_name"
	keyTenantDomain                  = "tenant_domain"
	keyTenantID                      = "tenant_id"
)
